### ISSUE TITLE
License

### ISSUE THREAD

**Issue by stgarf** [npinto/megaclisas-status#9]
Can you possibly add a license to this? Thanks!

Preferably MIT or BSD but obviously your code, your choice :).

**Comment by stgarf** [comment]
@npinto This should be a  helpful [resource](https://help.github.com/articles/open-source-licensing/) to add a license...

**Comment by npinto** [comment]
Agreed! But I'm not the original author :)

**Comment by stgarf** [comment]
@npinto Ah whoops! I've found it and looks like he's released it under GLPv2
https://github.com/eLvErDe/hwraid/blob/master/LICENSE

Sorry, please delete me :)
